### ISSUE TITLE
"You don't have any badges!"

### ISSUE THREAD

**Issue by Gameplayer8850** [plugdj/Issues-and-Reports#10]
#### OS/Browser Name and Version
Device: Sony Xperia Z3
Version: Android 6.0.1

#### I have tried
- [x] Reloading the page/app
- [ ] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [ ] Disabling all extensions and scripts (browser only)
- [x] Reinstalling the app (mobile only)

#### Description, Images, Logs
Under my badges i am able to see inscription: "You don't have any badges!".
https://imgur.com/a/xEGlS

##### Steps to reproduce:
1. Open app.
2. Go to "My Badges"

#### plug.dj username, profile link or user ID
Username: Gameplayer8850
ID: 13065138

**Comment by xSidewinderx** [comment]
I dont seem to have this issue on my device
Sidewinder:3482734
Android version: 6.0.1

**Comment by jaaaaanis** [comment]
popped up for me for about 0.5 secs, when i loaded the app for first time.. but after that everything worked fine.. can't see this as an issue at my end.
android version: 7.0
