### ISSUE TITLE
Community staff isn't opening in guest login

### ISSUE THREAD

**Issue by jaaaaanis** [plugdj/Issues-and-Reports#11]
#### I have tried
- [X] Reloading the page/app
- [X] Clearing (browser) cache, cookies or (mobile) app data
- [X] Switching to the default language (English)
- [ ] Disabling all extensions and scripts (browser only)
- [X] Reinstalling the app (mobile only)

#### Description, Images, Logs
When you login as a guest and want to open the community staff - nothing happens. App is not giving you any error or such. Screenshot below.
https://i.imgur.com/xV6ksv6.png

##### Steps to reproduce:
1. Open the app.
2. Login as a guest.
3. Enter any room.
4. Tap on the icon next to the room name at the right and then tap on the community staff icon.

#### plug.dj username, profile link or user ID
imperiālists, id: 3983716

**Comment by Dazzuh** [comment]
Guests can't view the community staff list by design, this menu shouldn't show at all.

**Comment by jaaaaanis** [comment]
Yes, including DJ Waitlist.. it should be removed as well for guests.
