### ISSUE TITLE
Visual bug (invisible user) in guest login

### ISSUE THREAD

**Issue by jaaaaanis** [plugdj/Issues-and-Reports#13]
#### I have tried
- [X] Reloading the page/app
- [X] Clearing (browser) cache, cookies or (mobile) app data
- [X] Switching to the default language (English)
- [ ] Disabling all extensions and scripts (browser only)
- [X] Reinstalling the app (mobile only)

#### Description, Images, Logs
After opening "People here now" section in guest login, i can see one invisible person under the staff and subscribers in every single room. Screenshots below.
https://i.imgur.com/Nl7FuUh.png
https://i.imgur.com/aLNOAZa.png

##### Steps to reproduce:
1. Open the app.
2. Login as a guest.
3. Enter any room.
4. Tap on the icon next to the room name at the right and then tap on the "people here now" icon.

#### plug.dj username, profile link or user ID
imperiālists, 3983716

**Comment by xSidewinderx** [comment]
Confirming same issue with mine.
Device: lg x power
Android version: 6.0.1
App Version: 2.6.7 Beta
Sidewinder:3482734
