### ISSUE TITLE
& is displayed as &amp;

### ISSUE THREAD

**Issue by Hasztagg** [plugdj/Issues-and-Reports#17]
#### plug.dj version
plug.dj Version 2.6.10

#### OS/Browser Name and Version
Lenovo Moto Z Play Android 7.1.1

#### I have tried
- [x] Reloading the page/app
- [ ] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [ ] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
Having a nickname of consisting of an ampersand causes it to be displayed as `&amp;`

#### plug.dj username, profile link or user ID
Tagzz
https://plug.dj/@/Tagzz

**Comment by Burkes** [comment]
@Hasztagg Is it only "&" or other entities as well? (like as < >)

**Comment by Hasztagg** [comment]
@Burkes Tested with `123!#$%^&*()-[]:'|;\` and only `&` caused the issue described above.

**Comment by Hasztagg** [comment]
I have actually just witnessed a person with `<3` in their username which turned into `&gt;`
