### ISSUE TITLE
Community Welcome Pop-up in Small Browser Cannot Be Scrolled

### ISSUE THREAD

**Issue by weisbergbrett** [plugdj/Issues-and-Reports#27]
#### I have tried
- [x] Reloading the page/app
- [x] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

##### Steps to reproduce:
1. On Google Chrome on Mac, keep the browser minimized
2. Make sure to remove all cookies on staging so pop-up welcome message displays
3. Join a community and try to scroll down on the page

**Comment by santiagorgb** [comment]
Hey @weisbergbrett , we've added a small fix for this and already deployed it (modal won't support scroll at least for now but we've made small adjustments so that the button don't get hidden). Anyways if you'd like us to adjust it more please let me know of course. Thanks!
