### ISSUE TITLE
Playlist bar still says "Add a song to play" when you already have media in a playlist

### ISSUE THREAD

**Issue by Dazzuh** [plugdj/Issues-and-Reports#28]
#### I have tried
- [x] Reloading the page/app
- [ ] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
https://i.dazzuh.xyz/yxyG.png
##### Steps to reproduce:
1. Add a song to the active playlist

#### plug.dj username, profile link or user ID
Dazzuh

**Comment by xBytez** [comment]
A fix for this has been deployed on stage. Closing this issue. Please re-open if it's still not working.
