### ISSUE TITLE
After entering some UI elements as a guest, a "Session Expired" alert appears

### ISSUE THREAD

**Issue by Hasztagg** [plugdj/Issues-and-Reports#29]
#### plug.dj version
1.5.6.11256

#### OS/Browser Name and Version
Windows 10/Microsoft Edge 41.16299.248.0

#### I have tried
- [x] Reloading the page/app
- [ ] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
After entering a community as a guest, a session expired alert (401) appears after entering: Shop, My Stuff, Recently Played. Also, configuring settings like "Only Show Friend Avatars" causes that message to appear.
##### Steps to reproduce:
1. Join a community as a guest.
2. Try accessing the shop, my stuff, etc.
3. Get "Session Expired" error.

#### plug.dj username, profile link or user ID
Tagzz
https://plug.dj/@/Tagzz

**Comment by Dazzuh** [comment]
Seems like this one has been fixed, closing this for now.
