### ISSUE TITLE
Not correctly showing room

### ISSUE THREAD

**Issue by xSidewinderx** [plugdj/Issues-and-Reports#3]
Mobile Application:
Android version: 6.0.1

#### I have tried
- [x] Reloading the page/app
- [x] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [ ] Disabling all extensions and scripts (browser only)
- [x] Reinstalling the app (mobile only)

#### Description, Images, Logs
Second account is in the room "test" but viewing from the friends list shows it at the dashboard.
Other rooms iv tested to see if I had the same issue seem to be working as of now. Possibility of other rooms being affected just unsure of cause.
https://gyazo.com/26b0c94285ecdfc0a15a6d85704083d0
https://gyazo.com/36df8ec9bbade29bfd304c532be3c3ad

#### plug.dj username, profile link or user ID
Sidewinder:3482734

**Comment by Dazzuh** [comment]
Looks like the "test" room is just a debug/private room, hence this is working as intended.
