### ISSUE TITLE
Multiple issues with the friends list

### ISSUE THREAD

**Issue by Dazzuh** [plugdj/Issues-and-Reports#30]
#### I have tried
- [x] Reloading the page/app
- [x] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
Whilst you're on the dashboard, the friends list title and search bar is pushed down resulting in it being behind the actual list, [Image](https://i.dazzuh.xyz/XqXK.png).

When you're in a room the list is down and slightly off to the left, [Image](https://i.dazzuh.xyz/n2ZC.png).

Setting a filter, switching to a different tab (such as chat) then back to friends list will keep the text in the filter but not actually apply it, [Image](https://i.dazzuh.xyz/AWJv.png).

#### plug.dj username, profile link or user ID
Dazzuh

**Comment by leticiapeuser** [comment]
thank you @Dazzuh this fix is deployed 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/6050346/38163749-89c9f0aa-34cf-11e8-8303-9832ab01f595.png">
