### ISSUE TITLE
Missing space in new vote popup

### ISSUE THREAD

**Issue by Dazzuh** [plugdj/Issues-and-Reports#34]
#### I have tried
- [x] Reloading the page/app
- [x] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
The new "like the song?" vote popup is missing a space between "appreciation" and "and"

![image](https://i.dazzuh.xyz/D9U7.png)

#### plug.dj username, profile link or user ID
Dazzuh

**Comment by leticiapeuser** [comment]
thank you @Dazzuh fixed :)
