### ISSUE TITLE
Song name on hover not updating

### ISSUE THREAD

**Issue by PamphletMP** [plugdj/Issues-and-Reports#42]
#### OS/Browser Name and Version
Google Chrome 64.0.3282.140

#### I have tried
- [x] Reloading the page/app
- [x] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
![image](https://user-images.githubusercontent.com/8618581/39793410-64b77d98-5313-11e8-82e0-df0f0dfa3925.png)
When a new song starts, the song name displayed when hovering does not change. The song name displayed is of the song playing when you join the room. Joining a different room does not change the hover song name. Reloading the page will update the hover song name.

##### Steps to reproduce:
1. Join a room.
2. Allow the current song to finish playing and the next one to start.
3. Hover over the name of the song currently being played at the bottom of the screen.

#### plug.dj username, profile link or user ID
[Pamphlet](https://plug.dj/@/pamphlet) 6330968

**Comment by Burkes** [comment]
Fixed in version 1.6.1.11789
