### ISSUE TITLE
Settings button invisible & Join Date text too large for small screen resolution

### ISSUE THREAD

**Issue by thedark1337** [plugdj/Issues-and-Reports#44]
### PLATFORM Issue
Web App Issue

#### plug.dj version
Plug.dj Web Version 1.6.0.11743

#### OS/Browser Name and Version
Windows 10 Home 1709 16299.371, 67.0.3396.30 (Official Build) beta (64-bit) (cohort: Beta)

#### I have tried
- [x] Reloading the page/app
- [x] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
http://i.tfle.xyz/2018-05-08_22-15-10.png
http://i.tfle.xyz/2018-05-08_22-15-51.png

##### Steps to reproduce:

Click on the settings menu  via any means, easiest being the avatar at the top right
The settings button is not visible on the screen resolution of 1366x768

Click on the friends menu via any means, easiest being the avatar at the top right
The join date is way too large.

#### plug.dj username, profile link or user ID

https://plug.dj/@/thedark1337-plug-dev

**Comment by Burkes** [comment]
I think the user cards are too big for this resolution rather than Join dates, the username is not even at it's maximum length and it's just barely showing up.

Maybe a horizontal view would look better where the avatar is smaller and the buttons (profile/accept and remove/ignore) are below the info.

**Comment by Burkes** [comment]
Fixed in version 1.6.1.11789.

They're a lot more responsive.
