### ISSUE TITLE
Volume slider animates when dragging

### ISSUE THREAD

**Issue by goto-bus-stop** [plugdj/Issues-and-Reports#47]
#### plug.dj version
Web 1.6.0.11743

#### OS/Browser Name and Version
Arch Linux + Chromium 66

#### Description
An animating slider is cool with keyboard controls, but when dragging it feels very sluggish and is confusing. When dragging with the mouse, the volume slider should not animate, but instead follow the cursor as precisely as possible. (It probably should also jump immediately on click so the feedback is instant.)

#### Steps to reproduce:
1. Drag the volume slider with the mouse.
2. The bar lags behind your cursor for a while because it animates to the target position.

**Comment by Burkes** [comment]
Fixed in version 1.6.1.11789.
