### ISSUE TITLE
Woots, Mehs & Grabs not visible through avatars

### ISSUE THREAD

**Issue by xUnique1k** [plugdj/Issues-and-Reports#49]
Names of people who Wooted, Mehed or Grabbed a song are covered behind the avatars as shown on the screenshot below.

![screenshot_1](https://user-images.githubusercontent.com/27681804/39835638-0809e608-53d1-11e8-992c-49811a2b7d1a.png)

**Comment by Friskygote** [comment]
It's RCS related feature.

**Comment by WiBla** [comment]
Closing this as this is unrelated to vanilla plug.
