### ISSUE TITLE
Volume slider not changing with scroll wheel

### ISSUE THREAD

**Issue by will-ng** [plugdj/Issues-and-Reports#52]
#### OS/Browser Name and Version
Google Chrome 66.0.3359.139

#### I have tried
- [x] Reloading the page/app
- [ ] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
In the past the volume would adjust by 5% by every "click" of the scroll wheel. However this does not seem to be functioning properly.

#### Steps to reproduce:
1. Mouse over the volume bar and use scroll wheel up and down
2. Notice whether or not the volume changes with scroll

#### plug.dj username, profile link or user ID
[Pamphlet](https://plug.dj/@/pamphlet) 6330968

**Comment by Dazzuh** [comment]
Plug.dj's volume has never adjusted with the scroll wheel. this feature is added by both RCS and PlugCubed.

Closing as this is unrelated to plug.
