### ISSUE TITLE
Queued track takes VERY long to update

### ISSUE THREAD

**Issue by Burkes** [plugdj/Issues-and-Reports#53]
#### OS/Browser Name and Version
Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)

#### I have tried
- [x] Reloading the page/app
- [x] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
When you switch, update playlists or finishes playing, the next song you will play, displayed at the bottom corner, takes VERY long to update and in some cases doesn't update at all. This is very unintuitive.
![image](https://i.imgur.com/vYJG8ub.png)

#### Steps to reproduce:
1. Switch playlists
or
1. Add a new media to your playlist
or
1. Play songs while monitoring the bottom left corner

#### plug.dj username, profile link or user ID
[@Burkes](https://plug.dj/@/burkes) (3703511)

**Comment by WiBla** [comment]
I think it only updates in two cases:
- If you click another playlist and come back to the active one
- When an advance event occurs

**Comment by Burkes** [comment]
Fixed in version 1.6.1.11789.
