### ISSUE TITLE
Settings button hidden on low screen res

### ISSUE THREAD

**Issue by thedark1337** [plugdj/Issues-and-Reports#67]
### PLATFORM Issue
Web App Issue

#### plug.dj version
Plug.dj Web Version 1.6.1.11789

#### OS/Browser Name and Version
Windows 10 Home 1709 16299.371, 67.0.3396.30 (Official Build) beta (64-bit) (cohort: Beta)

#### I have tried
- [x] Reloading the page/app
- [x] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
As seen in the following screenshot, the settings button is not visible
http://i.tfle.xyz/2018-05-11_20-56-10.png
Screen resolution: 1366x768
##### Steps to reproduce:

Click on the settings menu via any means, easiest being the avatar at the top right
The settings button is not visible

#### plug.dj username, profile link or user ID

https://plug.dj/@/thedark1337-plug-dev

**Comment by WiBla** [comment]
Fixed as of version 1.6.1.11804.

The menu is now hidden in smaller resolution, you can still select which panel you want to see by clicking your avatar in the top right of the screen:
![](https://i.imgur.com/9JefkRl.png)
