### ISSUE TITLE
Shift in sidebar icons when selecting Communities or Shop

### ISSUE THREAD

**Issue by will-ng** [plugdj/Issues-and-Reports#74]
#### OS/Browser Name and Version
Chrome 66.0.3359.139

#### I have tried
- [x] Reloading the page/app
- [x] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
![image](https://user-images.githubusercontent.com/8618581/39963475-c8a151a2-5639-11e8-8f4c-10ca538691bb.png)
Left: Current Room tab selected
Right: Communities tab selected

Switching between the current room tab and communities or shop tab causes the icons to shift. Spacing between the menu icons and top icon (headphones or arrow) change depending on what tab is selected.
#### Steps to reproduce:
1. Select current room tab on left. Already selected by default.
2. Select either Communities or Shop tab.

#### plug.dj username, profile link or user ID
[Pamphlet](https://plug.dj/@/pamphlet) 6330968

**Comment by WiBla** [comment]
Fixed as of version 1.6.1.11804.
