### ISSUE TITLE
Nothing happens when clicking on avatars in room

### ISSUE THREAD

**Issue by drewdorris** [plugdj/Issues-and-Reports#83]
#### I have tried
- [x] Reloading the page/app
- [x] Clearing (browser) cache, cookies or (mobile) app data
- [x] Switching to the default language (English)
- [x] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs

Clicking on an avatar doesn't pull up the menu for user settings:
![](https://i.imgur.com/4nvJytG.png)
Both hovering and clicking on the user currently DJing does nothing either, so skipping/etc. is impossible:
![](https://i.imgur.com/WD8DASO.png)

#### Steps to reproduce:
1. Go to a community
2. Hover over/click an avatar

#### plug.dj username, profile link or user ID
[StupidDrew9](https://plug.dj/@/stupiddrew9)

**Comment by WiBla** [comment]
This feature is working fine on my end, could you maybe provide us with a screenshot of your console (f12) ?
![](https://i.imgur.com/Sjk1bSe.png)

**Comment by drewdorris** [comment]
Doesn't look like I'm getting anything related to attempting to click/hover avatars
![](https://i.imgur.com/zqh3XQX.png)

Seems to work fine in Chrome

**Comment by Berd74** [comment]
Plug.dj support only majors web browsers (Chrome & Firefox latest versions).
I tested this feature on Chrome Version 68.0.3440.10 and Firefox Version 61.0.2 and everything seems to work fine.

**Comment by drewdorris** [comment]
Gotcha. Maybe should leave out [the unsupported browsers here](https://github.com/plugdj/Issues-and-Reports/blob/master/.github/CONTRIBUTING.md#others), haha

**Comment by drewdorris** [comment]
Actually seems to be working on Vivaldi now. Thanks guys
