### ISSUE TITLE
When selecting a playlist, no songs show up on the right

### ISSUE THREAD

**Issue by forkn** [plugdj/Issues-and-Reports#89]
This is after the most recent UI change. Using Chrome 49.0.2623.112 (64-bit) with no extensions or ad blocks.

#### I have tried
- [ ] Reloading the page/app
- [ ] Clearing (browser) cache, cookies or (mobile) app data
- [ ] Switching to the default language (English)
- [ ] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Steps to reproduce:
1. Step one.
2. Step two.
3. Uninteded behavior effect.

**Comment by weisbergbrett** [comment]
Not enough details.
