### ISSUE TITLE
Throttling breaks bots some times

### ISSUE THREAD

**Issue by mortenn** [plugdj/Issues-and-Reports#90]
#### I have tried
- [ ] Reloading the page/app
- [ ] Clearing (browser) cache, cookies or (mobile) app data
- [ ] Switching to the default language (English)
- [ ] Disabling all extensions and scripts (browser only)
- [ ] Reinstalling the app (mobile only)

#### Description, Images, Logs
When running a bot, and several banned songs are played in a row (such as trolls playing ear rape videos), the bot will stop working as the chained skip events apparently get throttled.

#### Steps to reproduce:
1. Wait for trolls
2. Watch the bot start skipping them
3. After one or two skips, the skip doesn't happen, but the bot saying it is skipping still happens

#### plug.dj username, profile link or user ID
KawaiiBot

**Comment by mortenn** [comment]
I suggest implementing API keys for bots as one part of fixing this issue.

**Comment by xBytez** [comment]
We'd still have throttles for bots just as much as users would be throttled. You must be chain-skipping very rapidly in order to hit the throttle. Tagging and closing this as "wontfix" for now.

**Comment by mortenn** [comment]
When 3 trolls are skipped within a few seconds of each other, bot stops skipping them.
Seems a bit too aggressive to me, and it leaves trolls the winners.

**Comment by Uricorn** [comment]
@xBytez trolls come in groups.

![capture](https://user-images.githubusercontent.com/5571265/44626719-060c7380-a92a-11e8-8b49-37c5ec0c7702.png)

**Comment by xBytez** [comment]
Do you have any error codes? Are you receiving a 429 from nginx or are you getting another error? I'm willing to tweak the skip endpoint specifically if it's needed.
